name: agents-md
version: 1.0.0
description: Agent-friendly workspace documentation (AGENTS.md)
author: workspace-recipes
license: MIT
tags:
  - agents
  - documentation
  - ai

variables:
  filename:
    type: string
    default: AGENTS.md
    options:
      - AGENTS.md
      - CLAUDE.md
    description: Primary agent documentation filename

generates:
  - path: AGENTS.md
    template: templates/AGENTS.md.hbs
    overwrite: false

validates:
  - check: file_exists
    path: AGENTS.md
    message: AGENTS.md is missing

tests:
  - name: creates AGENTS.md
    assert_file_exists: AGENTS.md

  - name: has quick start section
    assert_file_contains:
      path: AGENTS.md
      contains: "## Quick Start"

  - name: has workspace commands section
    assert_file_contains:
      path: AGENTS.md
      contains: "## Workspace Commands"

  - name: mentions workspace validate
    assert_file_contains:
      path: AGENTS.md
      contains: "workspace validate"
